### ISSUE TITLE
Bigserial type mismatch with kysely-codegen

### ISSUE THREAD

**Issue by AlexandrLi** [serverless-stack/kysely-data-api#17]
Hello guys,
After migrating sst to kysely-codegen I found inconsistency in 'bigserial' type.
The whole details could be found in this thread: https://github.com/RobinBlomberg/kysely-codegen/issues/31
I checked the source code and looks like 'bigint' is parsed as number by query-compiler (https://github.com/serverless-stack/kysely-data-api/blob/master/src/data-api-query-compiler.ts#L36). I think it may lead to some other inconsistencies which should be aligned with kysely-codegen. In other case it does not make sense to use type autogeneration and manually edit types everytime.
What do you think on this?

**Comment by AlexandrLi** [comment]
@thdxr any thoughts on this?

**Comment by thdxr** [comment]
Would accept a PR for a fix
