### ISSUE TITLE
When selecting array of floats, the result is wrapped in an object with "doubleValues"

### ISSUE THREAD

**Issue by jo-sip** [serverless-stack/kysely-data-api#22]
e.g 
```
  console.log(
    await db
      .selectFrom("comments")
      .select("embedding")
      .execute()
      .then((r) => r[0].embedding),
  );
  ```
Prints: `{ doubleValues: [ 4, 5, 6 ] }`.

I'd expect it to unwrap the array.

This is the schema from `db.introspection`

```
  {
    name: 'embedding',
    dataType: '_float4',
    dataTypeSchema: 'pg_catalog',
    isNullable: true,
    isAutoIncrementing: false,
    hasDefaultValue: false
  }
```

Looks like its perhaps just passing the result through? https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ArrayValue.html

**Comment by jayair** [comment]
Is this more of a question for Kysely?

**Comment by igalklebanov** [comment]
> Is this more of a question for Kysely?

Hey 👋 

This is an AWS Data API specific structure. 
The current implementation of this dialect's driver doesn't unmarshall `arrayValue` objects so consumers don't get JS arrays in such fields.

**Comment by jayair** [comment]
Ah I see. Thanks!
