### ISSUE TITLE
Support for AWS SDK v3?

### ISSUE THREAD

**Issue by JohnMarsden24** [serverless-stack/kysely-data-api#4]
In the constructor the instructions tell you to instantiate a `RDSDataService` for the driver client however that relies on `aws-sdk` versions less than v3, which has dropped the `RDSDataService` construct in favour of [RDSDataClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-rds-data/classes/rdsdataclient.html). Is there any plans to support this in the future?

**Comment by thdxr** [comment]
Yes! I ran into this myself a few days ago and I'll upgrade this soon

**Comment by Gr33nLight** [comment]
Hey, did you manage to find a solution for this? I'm trying to use this connector, but I'm having trouble instantiating the client.
Thanks

**Comment by JohnMarsden24** [comment]
> Hey, did you manage to find a solution for this? I'm trying to use this connector, but I'm having trouble instantiating the client. Thanks

Looks like this hasn't been implemented yet and still relies on `aws-sdk`. If it's any help this is how we create the client:

```typescript
import { RDSDataService } from 'aws-sdk';
import { Kysely } from 'kysely';
import { DataApiDialect } from 'kysely-data-api';

import type { IAddress } from '../datasources/Address';
import type { IUser } from '../datasources/User';

export interface IDatabase {
  users: IUser;
  addresses: IAddress;
}

export class Database {
  private readonly db: Kysely<IDatabase>;

  public constructor() {
    this.db = this.createClient();
  }

  public get getDatabase(): Kysely<IDatabase> {
    return this.db;
  }

  private createClient() {
    return new Kysely({
      dialect: new DataApiDialect({
        mode: 'postgres',
        driver: {
          secretArn: process.env.SECRET_ARN as string,
          resourceArn: process.env.CLUSTER_ARN as string,
          database: process.env.DATABASE as string,
          client: new RDSDataService(),
        },
      }),
    });
  }
}
```

**Comment by Newbie012** [comment]
I made a PR that should fix it (breaking change) - https://github.com/serverless-stack/kysely-data-api/pull/18
